### PR TITLE
Make compatible with PHP v8.1

### PR DESCRIPTION
**Pull request by mitrii**

### CODE REVIEW

**Comment by abellion** [comment]
Hey @mitrii,

The library is already compatible with PHP > 8.0. It misses the return types you added, but because it's a PHP > 8.0 only feature, this would break compatibility with PHP > 7.1 (which we support).

Besides, what's the reason for the `ext-json` requirement ?

**Comment by mitrii** [comment]
Hi

Sorry, my mistake. Now, I'm replaced return type `mixed` with attribute `#[\ReturnTypeWillChange]` for compatibility with PHP > 7.1

**Comment by abellion** [comment]
What's the benefit of it ? It's a bit misleading because the return type won't change, it will just be specified. I would rather wait for when we will drop PHP 7 support.

**Comment by mitrii** [comment]
This prevents to trigger E_DEPRECATION notice in PHP 8.1, until support for PHP 7  is dropped

**Comment by abellion** [comment]
Thank you @mitrii !

**Pull request merged**
